base_images:
  base:
    name: "4.14"
    namespace: ocp
    tag: cli
  ocp_builder_rhel-8-golang-1.19-openshift-4.14:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.19-openshift-4.14
build_root:
  from_repository: true
images:
- context_dir: "2"
  dockerfile_path: Dockerfile.rhel8
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.19-openshift-4.14:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.14
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/2/.
  to: jenkins
- context_dir: slave-base
  dockerfile_path: Dockerfile.rhel8
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.19-openshift-4.14:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.14
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/slave-base/.
  to: jenkins-agent-base
- context_dir: agent-maven
  dockerfile_path: Dockerfile.rhel8
  from: jenkins-agent-base
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/agent-maven/.
  to: jenkins-agent-maven
- context_dir: agent-nodejs-12
  dockerfile_path: Dockerfile.rhel8
  from: jenkins-agent-base
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift/jenkins/agent-nodejs-12/.
  to: jenkins-agent-nodejs
promotion:
  name: "4.14"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
  openshift-4-11:
    integration:
      name: "4.11"
      namespace: ocp
  openshift-4-12:
    integration:
      name: "4.12"
      namespace: ocp
  openshift-4-13:
    integration:
      name: "4.13"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: jenkins-check-plugins-supply-chain-change
  commands: hack/check-plugins-supply-chain-change.sh
  container:
    clone: true
    from: ocp_builder_rhel-8-golang-1.19-openshift-4.14
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: e2e-jenkins-image-tests
  commands: IMAGE_NAME=stable:jenkins make smoke
  container:
    clone: true
    from: ocp_builder_rhel-8-golang-1.19-openshift-4.14
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: e2e-aws-openshift-4-14
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:latest
    workflow: openshift-e2e-aws
- as: e2e-aws-openshift-4-13
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-13
    workflow: openshift-e2e-aws
- as: e2e-aws-openshift-4-12
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-12
    workflow: openshift-e2e-aws
- as: e2e-aws-openshift-4-11
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-11
    workflow: openshift-e2e-aws
- as: e2e-aws-jenkins-sync-plugin-openshift-4-14
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:latest
    test:
    - ref: jenkins-sync-plugin-e2e
    workflow: ipi-aws
- as: e2e-aws-jenkins-sync-plugin-openshift-4-13
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-13
    test:
    - ref: jenkins-sync-plugin-e2e
    workflow: ipi-aws
- as: e2e-aws-jenkins-sync-plugin-openshift-4-12
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-12
    test:
    - ref: jenkins-sync-plugin-e2e
    workflow: ipi-aws
- as: e2e-aws-jenkins-sync-plugin-openshift-4-11
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-11
    test:
    - ref: jenkins-sync-plugin-e2e
    workflow: ipi-aws
- as: e2e-aws-jenkins-client-plugin-openshift-4-14
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:latest
    test:
    - ref: jenkins-client-plugin-tests
    workflow: ipi-aws
- as: e2e-aws-jenkins-client-plugin-openshift-4-13
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-13
    test:
    - ref: jenkins-client-plugin-tests
    workflow: ipi-aws
- as: e2e-aws-jenkins-client-plugin-openshift-4-12
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-12
    test:
    - ref: jenkins-client-plugin-tests
    workflow: ipi-aws
- as: e2e-aws-jenkins-client-plugin-openshift-4-11
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      RELEASE_IMAGE_LATEST: release:openshift-4-11
    test:
    - ref: jenkins-client-plugin-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: jenkins
